ALTER TABLE sessions ADD COLUMN mode TEXT NOT NULL DEFAULT 'listen';
ALTER TABLE settings ADD COLUMN context TEXT NOT NULL DEFAULT '';
ALTER TABLE settings ADD COLUMN persona TEXT NOT NULL DEFAULT '';
